services:
  - type: web
    name: interview-app
    env: node
    buildCommand: npm ci && npm run build:web
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
        fromSecret: SUPABASE_ANON_KEY
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: SUPABASE_SERVICE_ROLE_KEY
      - key: SESSION_SECRET
        fromSecret: SESSION_SECRET
      - key: PUBLIC_BASE_URL
        fromSecret: PUBLIC_BASE_URL
      - key: OPENAI_REALTIME_MODEL
        value: gpt-4o-mini-realtime-preview-2024-12-17
      - key: FOLLOWUP_IMMEDIATE_MICROCALL
        value: 1